"""
Database Models
Defines all tables used in the project with SQLAlchemy ORM.
Each class below becomes one table in the SQLite database.
"""

from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

# This db object is created here and imported into app.py to avoid circular imports
db = SQLAlchemy()


class Owner(db.Model):
    """Stores vehicle owner details (simulated RTO data)."""
    __tablename__ = "owners"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    phone_number = db.Column(db.String(20), nullable=False)
    email = db.Column(db.String(100), nullable=True)

    # One owner can have many vehicles
    vehicles = db.relationship("Vehicle", backref="owner", lazy=True)


class Vehicle(db.Model):
    """Stores registered vehicle details."""
    __tablename__ = "vehicles"

    id = db.Column(db.Integer, primary_key=True)
    vehicle_number = db.Column(db.String(20), unique=True, nullable=False)
    vehicle_type = db.Column(db.String(50), nullable=True)  # car, bike, truck, etc.
    owner_id = db.Column(db.Integer, db.ForeignKey("owners.id"), nullable=True)

    # Helper contact numbers (family/emergency contacts)
    helper1_phone = db.Column(db.String(20), nullable=True)
    helper2_phone = db.Column(db.String(20), nullable=True)


class Alert(db.Model):
    """Stores every accident/overspeed alert generated by the system."""
    __tablename__ = "alerts"

    id = db.Column(db.Integer, primary_key=True)
    vehicle_number = db.Column(db.String(20), nullable=False)
    alert_type = db.Column(db.String(50), nullable=False)  # "Accident" or "Overspeed"
    speed = db.Column(db.Float, nullable=True)  # km/h at time of alert

    # Simulated GPS location of the incident
    latitude = db.Column(db.Float, nullable=True)
    longitude = db.Column(db.Float, nullable=True)

    # Nearest services found at time of alert (stored for quick dashboard display)
    nearest_hospital = db.Column(db.String(100), nullable=True)
    nearest_police_station = db.Column(db.String(100), nullable=True)

    # Notification status
    sms_sent = db.Column(db.Boolean, default=False)
    email_sent = db.Column(db.Boolean, default=False)

    timestamp = db.Column(db.DateTime, default=datetime.utcnow)


class FastagHistory(db.Model):
    """Simulated FASTag toll crossing history for a vehicle."""
    __tablename__ = "fastag_history"

    id = db.Column(db.Integer, primary_key=True)
    vehicle_number = db.Column(db.String(20), nullable=False)
    toll_name = db.Column(db.String(100), nullable=False)
    city = db.Column(db.String(100), nullable=False)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)


class Hospital(db.Model):
    """Simulated nearby hospital database."""
    __tablename__ = "hospitals"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    latitude = db.Column(db.Float, nullable=False)
    longitude = db.Column(db.Float, nullable=False)
    phone_number = db.Column(db.String(20), nullable=True)


class PoliceStation(db.Model):
    """Simulated nearby police station database."""
    __tablename__ = "police_stations"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    latitude = db.Column(db.Float, nullable=False)
    longitude = db.Column(db.Float, nullable=False)
    phone_number = db.Column(db.String(20), nullable=True)
